"""“auth_is_active_column”

Revision ID: 06fd7fad588c
Revises: df3d02f219e5
Create Date: 2025-03-31 15:03:12.491948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06fd7fad588c'
down_revision: Union[str, None] = 'df3d02f219e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('auth', sa.Column('role', sa.String(), nullable=False))
    op.add_column('invoice_summaries', sa.Column('client_summary_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'invoice_summaries', 'client_summaries', ['client_summary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_summaries', type_='foreignkey')
    op.drop_column('invoice_summaries', 'client_summary_id')
    op.drop_column('auth', 'role')
    op.drop_column('auth', 'is_active')
    # ### end Alembic commands ###
