"""companies_suscription

Revision ID: 4a1c43bb69ce
Revises: 4cf737ead86b
Create Date: 2025-06-04 15:28:25.636731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a1c43bb69ce"
down_revision: Union[str, None] = "4cf737ead86b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("subscription_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "companies", "subscriptions", ["subscription_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "companies", type_="foreignkey")
    op.drop_column("companies", "subscription_id")
    # ### end Alembic commands ###
