"""“username_to_email”

Revision ID: ba5443106668
Revises: f75dfd7ed4f8
Create Date: 2025-04-08 10:18:46.714341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5443106668'
down_revision: Union[str, None] = 'f75dfd7ed4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('email', sa.String(), nullable=False))
    op.drop_index('ix_auth_username', table_name='auth')
    op.create_index(op.f('ix_auth_email'), 'auth', ['email'], unique=True)
    op.drop_column('auth', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_auth_email'), table_name='auth')
    op.create_index('ix_auth_username', 'auth', ['username'], unique=True)
    op.drop_column('auth', 'email')
    # ### end Alembic commands ###
