"""subscription_limits_requests_count

Revision ID: db3320a7e30a
Revises: 4a1c43bb69ce
Create Date: 2025-06-04 18:58:13.762980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3320a7e30a'
down_revision: Union[str, None] = '4a1c43bb69ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('accountant_id', sa.UUID(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('last_request_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['accountant_id'], ['accountants.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscriptions', sa.Column('price', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('subscriptions', sa.Column('currency', sa.String(), nullable=False, server_default='GTQ'))
    op.add_column('subscriptions', sa.Column('invoices_limit', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('subscriptions', sa.Column('nit_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'nit_limit')
    op.drop_column('subscriptions', 'invoices_limit')
    op.drop_column('subscriptions', 'currency')
    op.drop_column('subscriptions', 'price')
    op.drop_table('invoice_requests')
    # ### end Alembic commands ###
